package routes

import (
	"net/http"

	"dnsc_microservice/internal/config"
	"dnsc_microservice/internal/handlers"
	"dnsc_microservice/internal/middleware"
	"dnsc_microservice/internal/services"

	"github.com/gorilla/mux"
)

// RegisterRoutes builds the HTTP handler with auth, reference and company APIs.
func RegisterRoutes(appServices *services.AppServices, cfg *config.Config) http.Handler {
	router := mux.NewRouter()

	handlers.RegisterSystemRoutes(router)

	api := router.PathPrefix("/api").Subrouter()

	authHandler := handlers.NewAuthHandler(appServices.Auth)
	api.HandleFunc("/auth/register", authHandler.Register).Methods(http.MethodPost)
	api.HandleFunc("/auth/login", authHandler.Login).Methods(http.MethodPost)
	api.HandleFunc("/auth/refresh", authHandler.Refresh).Methods(http.MethodPost)
	api.HandleFunc("/auth/logout", authHandler.Logout).Methods(http.MethodPost)
	api.HandleFunc("/auth/me", authHandler.Me).Methods(http.MethodGet)

	ref := handlers.NewReferenceHandler(appServices.Reference)
	api.HandleFunc("/countries", ref.ListCountries).Methods(http.MethodGet)
	api.HandleFunc("/countries/{id}", ref.GetCountry).Methods(http.MethodGet)
	api.HandleFunc("/cities", ref.ListCities).Methods(http.MethodGet)
	api.HandleFunc("/cities", ref.CreateCity).Methods(http.MethodPost)
	api.HandleFunc("/currencies", ref.ListCurrencies).Methods(http.MethodGet)
	api.HandleFunc("/currencies/{code}", ref.GetCurrency).Methods(http.MethodGet)
	api.HandleFunc("/um", ref.ListUms).Methods(http.MethodGet)
	api.HandleFunc("/um", ref.CreateUm).Methods(http.MethodPost)
	api.HandleFunc("/um/{idUm}", ref.GetUm).Methods(http.MethodGet)
	api.HandleFunc("/um/{idUm}", ref.UpdateUm).Methods(http.MethodPut)
	api.HandleFunc("/um/{idUm}", ref.DeleteUm).Methods(http.MethodDelete)
	api.HandleFunc("/officesType", ref.ListOfficeTypes).Methods(http.MethodGet)
	api.HandleFunc("/contactsroles", ref.ListContactRoles).Methods(http.MethodGet)
	api.HandleFunc("/paymentterms", ref.ListPaymentTerms).Methods(http.MethodGet)
	api.HandleFunc("/paymentterms", ref.CreatePaymentTerm).Methods(http.MethodPost)
	api.HandleFunc("/paymentterms/{id}", ref.GetPaymentTerm).Methods(http.MethodGet)

	co := handlers.NewCompanyHandler(appServices.Company)
	api.HandleFunc("/companies/{id}", co.GetCompany).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/accountcenter", co.ListAccountCenters).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/accountcenter", co.CreateAccountCenter).Methods(http.MethodPost)
	api.HandleFunc("/companysettings/accountcenter/{idAccountCenter}", co.GetAccountCenter).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/accountcenter/{idAccountCenter}", co.UpdateAccountCenter).Methods(http.MethodPut)
	api.HandleFunc("/companysettings/accountcenter/{idAccountCenter}", co.DeleteAccountCenter).Methods(http.MethodDelete)
	api.HandleFunc("/companysettings/accountcode", co.ListAccountCodes).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/bank", co.ListBanks).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/bank", co.CreateBank).Methods(http.MethodPost)
	api.HandleFunc("/companysettings/bank/{id}", co.GetBank).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/bank/{id}", co.UpdateBank).Methods(http.MethodPut)
	api.HandleFunc("/companysettings/bank/{id}", co.DeleteBank).Methods(http.MethodDelete)
	api.HandleFunc("/companysettings/bupnumerators", co.ListBupNumerators).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/currencychange/{idSourceCurr}", co.GetCurrencyChange).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/taxs", co.ListTaxs).Methods(http.MethodGet)
	api.HandleFunc("/companysettings/taxs/{idVat}", co.GetTax).Methods(http.MethodGet)

	ct := handlers.NewContactHandler(appServices.Contact)
	api.HandleFunc("/contacts", ct.ListContacts).Methods(http.MethodGet)
	api.HandleFunc("/contacts", ct.CreateContact).Methods(http.MethodPost)
	api.HandleFunc("/contacts/sources", ct.ListContactSources).Methods(http.MethodGet)
	api.HandleFunc("/contacts/{idcontact}", ct.GetContact).Methods(http.MethodGet)
	api.HandleFunc("/contacts/{idcontact}", ct.PatchContact).Methods(http.MethodPatch)
	api.HandleFunc("/contacts/{idcontact}", ct.DeleteContact).Methods(http.MethodDelete)
	api.HandleFunc("/contacts/{id}", ct.UpdateContact).Methods(http.MethodPut)
	api.HandleFunc("/contacts/{id}/photo", ct.UploadPhoto).Methods(http.MethodPost)
	api.HandleFunc("/contacts/{idcontact}/offices", ct.ListOffices).Methods(http.MethodGet)
	api.HandleFunc("/contacts/{idcontact}/offices", ct.CreateOffice).Methods(http.MethodPost)
	api.HandleFunc("/contacts/{idcontact}/offices/{idoffice}", ct.UpdateOffice).Methods(http.MethodPut)
	api.HandleFunc("/contacts/{idcontact}/offices/{idoffice}", ct.DeleteOffice).Methods(http.MethodDelete)
	api.HandleFunc("/contacts/{idcontact}/subcontacts", ct.ListSubContacts).Methods(http.MethodGet)
	api.HandleFunc("/contacts/{idcontact}/subcontacts", ct.CreateSubContact).Methods(http.MethodPost)
	api.HandleFunc("/contacts/{idcontact}/subcontacts/{idsubcontact}", ct.DeleteSubContact).Methods(http.MethodDelete)

	cu := handlers.NewCustomerHandler(appServices.Customer)
	api.HandleFunc("/customers", cu.ListCustomers).Methods(http.MethodGet)
	api.HandleFunc("/customers", cu.CreateCustomer).Methods(http.MethodPost)
	api.HandleFunc("/customers/{idcustomer}", cu.GetCustomer).Methods(http.MethodGet)
	api.HandleFunc("/customers/{idcustomer}", cu.UpdateCustomer).Methods(http.MethodPut)
	api.HandleFunc("/customers/{idcustomer}", cu.PatchCustomer).Methods(http.MethodPatch)
	api.HandleFunc("/customers/{idcustomer}", cu.DeleteCustomer).Methods(http.MethodDelete)
	api.HandleFunc("/customers/{idcustomer}/report", cu.GetCustomerReport).Methods(http.MethodGet)

	ve := handlers.NewVendorHandler(appServices.Vendor)
	api.HandleFunc("/vendors", ve.ListVendors).Methods(http.MethodGet)
	api.HandleFunc("/vendors", ve.CreateVendor).Methods(http.MethodPost)
	api.HandleFunc("/vendors/{idvendor}", ve.GetVendor).Methods(http.MethodGet)
	api.HandleFunc("/vendors/{idvendor}", ve.UpdateVendor).Methods(http.MethodPut)
	api.HandleFunc("/vendors/{idvendor}", ve.PatchVendor).Methods(http.MethodPatch)
	api.HandleFunc("/vendors/{idvendor}", ve.DeleteVendor).Methods(http.MethodDelete)
	api.HandleFunc("/vendors/{idvendor}/report", ve.GetVendorReport).Methods(http.MethodGet)

	pr := handlers.NewProductHandler(appServices.Product)
	api.HandleFunc("/products", pr.ListProducts).Methods(http.MethodGet)
	api.HandleFunc("/products/product", pr.CreateProduct).Methods(http.MethodPost)
	api.HandleFunc("/products/product", pr.UpdateProduct).Methods(http.MethodPut)
	api.HandleFunc("/products/{id}", pr.GetProduct).Methods(http.MethodGet)
	api.HandleFunc("/products/{id}/media", pr.LinkMedia).Methods(http.MethodPut)
	api.HandleFunc("/products/{id}/variants", pr.ListVariants).Methods(http.MethodGet)
	api.HandleFunc("/products/variants", pr.UpdateVariants).Methods(http.MethodPut)

	pg := handlers.NewProductGroupHandler(appServices.ProductGroup)
	api.HandleFunc("/productsgroups", pg.ListProductGroups).Methods(http.MethodGet)
	api.HandleFunc("/productsgroups", pg.CreateProductGroup).Methods(http.MethodPost)
	api.HandleFunc("/productsgroups/{id}", pg.GetProductGroup).Methods(http.MethodGet)
	api.HandleFunc("/productsgroups/{id}", pg.UpdateProductGroup).Methods(http.MethodPut)
	api.HandleFunc("/productsgroups/{id}", pg.DeleteProductGroup).Methods(http.MethodDelete)

	at := handlers.NewAttributeHandler(appServices.Attribute)
	api.HandleFunc("/attributes", at.ListAttributes).Methods(http.MethodGet)
	api.HandleFunc("/attributes", at.CreateAttributes).Methods(http.MethodPost)
	api.HandleFunc("/attributes/productattributes", at.ListProductCharacteristics).Methods(http.MethodGet)
	api.HandleFunc("/attributes/productattributes", at.CreateProductCharacteristic).Methods(http.MethodPost)
	api.HandleFunc("/attributes/productattributes", at.UpdateProductCharacteristic).Methods(http.MethodPut)

	pl := handlers.NewPricelistHandler(appServices.Pricelist)
	api.HandleFunc("/pricelists", pl.ListPricelists).Methods(http.MethodGet)
	api.HandleFunc("/pricelists", pl.CreatePricelist).Methods(http.MethodPost)
	api.HandleFunc("/pricelists/schemes", pl.ListPricelistSchemes).Methods(http.MethodGet)
	api.HandleFunc("/pricelists/schemes/{id}", pl.GetPricelistScheme).Methods(http.MethodGet)
	api.HandleFunc("/pricelists/{id}", pl.GetPricelist).Methods(http.MethodGet)
	api.HandleFunc("/pricelists/{id}", pl.UpdatePricelist).Methods(http.MethodPut)
	api.HandleFunc("/pricelists/{id}", pl.DeletePricelist).Methods(http.MethodDelete)

	stg := handlers.NewStorageHandler(appServices.Storage, appServices.StorageLocation)
	api.HandleFunc("/storages", stg.ListStorages).Methods(http.MethodGet)
	api.HandleFunc("/storages", stg.CreateStorage).Methods(http.MethodPost)
	api.HandleFunc("/storages/{idStorage}/storageLocations", stg.CreateNestedLocation).Methods(http.MethodPost)
	api.HandleFunc("/storages/{idStorage}/storageLocations/{idLocation}", stg.GetNestedLocation).Methods(http.MethodGet)
	api.HandleFunc("/storages/{idStorage}/storageLocations/{idLocation}", stg.UpdateNestedLocation).Methods(http.MethodPut)
	api.HandleFunc("/storages/{idStorage}/storageLocations/{idLocation}", stg.DeleteNestedLocation).Methods(http.MethodDelete)
	api.HandleFunc("/storages/{id}", stg.GetStorage).Methods(http.MethodGet)
	api.HandleFunc("/storages/{id}", stg.UpdateStorage).Methods(http.MethodPut)
	api.HandleFunc("/storages/{id}", stg.DeleteStorage).Methods(http.MethodDelete)

	sl := handlers.NewStorageLocationHandler(appServices.StorageLocation)
	api.HandleFunc("/storageLocations", sl.ListStorageLocations).Methods(http.MethodGet)
	api.HandleFunc("/storageLocations", sl.CreateStorageLocation).Methods(http.MethodPost)
	api.HandleFunc("/storageLocations/{idLocation}", sl.GetStorageLocation).Methods(http.MethodGet)
	api.HandleFunc("/storageLocations/{idLocation}", sl.UpdateStorageLocation).Methods(http.MethodPut)
	api.HandleFunc("/storageLocations/{idLocation}", sl.DeleteStorageLocation).Methods(http.MethodDelete)

	sk := handlers.NewStockHandler(appServices.Stock)
	api.HandleFunc("/stocks/avaibility/report", sk.ListAvailabilityReport).Methods(http.MethodGet)
	api.HandleFunc("/stocks/avaibility", sk.ListAvailability).Methods(http.MethodGet)
	api.HandleFunc("/stocks", sk.CreateStock).Methods(http.MethodPost)
	api.HandleFunc("/stocks", sk.UpdateStock).Methods(http.MethodPut)

	lt := handlers.NewLotHandler(appServices.Lot)
	api.HandleFunc("/lots", lt.ListLots).Methods(http.MethodGet)
	api.HandleFunc("/lots", lt.CreateLot).Methods(http.MethodPost)
	api.HandleFunc("/lots/{idLot}", lt.GetLot).Methods(http.MethodGet)
	api.HandleFunc("/lots/{idLot}", lt.UpdateLot).Methods(http.MethodPut)
	api.HandleFunc("/lots/{idlot}", lt.DeleteLot).Methods(http.MethodDelete)

	mdt := handlers.NewMachineDataTrackingHandler(appServices.MachineDataTracking)
	api.HandleFunc("/machineDataTracking/list", mdt.CreateBatch).Methods(http.MethodPost)
	api.HandleFunc("/machineDataTracking", mdt.List).Methods(http.MethodGet)
	api.HandleFunc("/machineDataTracking", mdt.Create).Methods(http.MethodPost)
	api.HandleFunc("/machineDataTracking/{id}", mdt.Get).Methods(http.MethodGet)
	api.HandleFunc("/machineDataTracking/{id}", mdt.Update).Methods(http.MethodPut)
	api.HandleFunc("/machineDataTracking/{id}", mdt.Delete).Methods(http.MethodDelete)

	sd := handlers.NewSaleDocumentHandler(appServices.SaleDocument)
	// SaleDocument — static paths before parameterized routes
	api.HandleFunc("/sales/offers", sd.ListOffers).Methods(http.MethodGet)
	api.HandleFunc("/sales/offers", sd.CreateOffer).Methods(http.MethodPost)
	api.HandleFunc("/sales/offers/{idDoc}/pdf", sd.GetOfferPDF).Methods(http.MethodGet)
	api.HandleFunc("/sales/orders", sd.ListOrders).Methods(http.MethodGet)
	api.HandleFunc("/sales/orders", sd.CreateOrder).Methods(http.MethodPost)
	api.HandleFunc("/sales/orders/{idDoc}/pdf", sd.GetOrderPDF).Methods(http.MethodGet)
	api.HandleFunc("/sales/goodsissue", sd.ListGoodsIssue).Methods(http.MethodGet)
	api.HandleFunc("/sales/goodsissue", sd.CreateGoodsIssue).Methods(http.MethodPost)
	api.HandleFunc("/sales/goodsissue/{idDoc}/pdf", sd.GetGoodsIssuePDF).Methods(http.MethodGet)
	api.HandleFunc("/sales/goodissuestoinvoice", sd.GoodsIssuesToInvoice).Methods(http.MethodPost)
	api.HandleFunc("/sales/invoices", sd.ListInvoices).Methods(http.MethodGet)
	api.HandleFunc("/sales/invoices", sd.CreateInvoice).Methods(http.MethodPost)
	api.HandleFunc("/sales/invoices/openbalance", sd.OpenBalance).Methods(http.MethodGet)
	api.HandleFunc("/sales/invoices/{idDoc}/pdf", sd.GetInvoicePDF).Methods(http.MethodGet)
	api.HandleFunc("/sales/invoices/{idDoc}/einvoice", sd.EInvoice).Methods(http.MethodPost)
	api.HandleFunc("/sales/invoices/{id}/payments", sd.AddInvoicePayment).Methods(http.MethodPost)
	api.HandleFunc("/sales/tickets", sd.ListTickets).Methods(http.MethodGet)
	api.HandleFunc("/sales/tickets", sd.CreateTicket).Methods(http.MethodPost)
	api.HandleFunc("/sales/writeoff", sd.CreateWriteoff).Methods(http.MethodPost)
	api.HandleFunc("/sales/customerpayment", sd.ListCustomerPayments).Methods(http.MethodGet)
	api.HandleFunc("/sales/customerpayment", sd.CreateCustomerPayment).Methods(http.MethodPost)
	api.HandleFunc("/sales/customerpayment/{id}", sd.GetCustomerPaymentByID).Methods(http.MethodGet)
	api.HandleFunc("/sales/reports", sd.Reports).Methods(http.MethodGet)
	api.HandleFunc("/sales/{idDoc}/pdf", sd.GetDocumentPDF).Methods(http.MethodGet)
	api.HandleFunc("/sales/{idDoc}/attachment", sd.GetAttachment).Methods(http.MethodGet)
	api.HandleFunc("/sales/{idDoc}/attachment", sd.UploadAttachment).Methods(http.MethodPost)
	api.HandleFunc("/sales/{idDoc}/attachment", sd.DeleteAttachment).Methods(http.MethodDelete)
	api.HandleFunc("/sales/{idDoc}/customerpayment", sd.GetCustomerPaymentByDoc).Methods(http.MethodGet)
	api.HandleFunc("/sales/{id}/offers", sd.GetOffer).Methods(http.MethodGet)
	api.HandleFunc("/sales/{id}/offers", sd.UpdateOffer).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/offers", sd.DeleteOffer).Methods(http.MethodDelete)
	api.HandleFunc("/sales/{id}/offerstogoodsissue", sd.OfferToGoodsIssue).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/offerstoinvoice", sd.OfferToInvoice).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/offerstoorder", sd.OfferToOrder).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/orders", sd.GetOrder).Methods(http.MethodGet)
	api.HandleFunc("/sales/{id}/orders", sd.UpdateOrder).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/orders", sd.DeleteOrder).Methods(http.MethodDelete)
	api.HandleFunc("/sales/{id}/orderspayments", sd.UpdateOrderPayments).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/orderstogoodsissue", sd.OrderToGoodsIssue).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/orderstoinvoice", sd.OrderToInvoice).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/orderstoticket", sd.OrderToTicket).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/goodsissue", sd.GetGoodsIssue).Methods(http.MethodGet)
	api.HandleFunc("/sales/{id}/goodsissue", sd.UpdateGoodsIssue).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/goodsissue", sd.DeleteGoodsIssue).Methods(http.MethodDelete)
	api.HandleFunc("/sales/{id}/goodissuetoinvoice", sd.GoodsIssueToInvoice).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/invoices", sd.GetInvoice).Methods(http.MethodGet)
	api.HandleFunc("/sales/{id}/invoices", sd.UpdateInvoice).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/invoices", sd.DeleteInvoice).Methods(http.MethodDelete)
	api.HandleFunc("/sales/{id}/invoicetocreditnote", sd.InvoiceToCreditNote).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/tickets", sd.GetTicket).Methods(http.MethodGet)
	api.HandleFunc("/sales/{id}/tickets", sd.UpdateTicket).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/tickets", sd.DeleteTicket).Methods(http.MethodDelete)
	api.HandleFunc("/sales/{id}/tickettowriteoff", sd.TicketToWriteoff).Methods(http.MethodPost)
	api.HandleFunc("/sales/{id}/writeoff", sd.UpdateWriteoff).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/customerpayment", sd.UpdateCustomerPayment).Methods(http.MethodPut)
	api.HandleFunc("/sales/{id}/customerpayment", sd.DeleteCustomerPayment).Methods(http.MethodDelete)

	pd := handlers.NewPurchaseDocumentHandler(appServices.PurchaseDocument)
	api.HandleFunc("/purchases/orders", pd.ListOrders).Methods(http.MethodGet)
	api.HandleFunc("/purchases/orders", pd.CreateOrder).Methods(http.MethodPost)
	api.HandleFunc("/purchases/orders/{idDoc}/pdf", pd.GetOrderPDF).Methods(http.MethodGet)
	api.HandleFunc("/purchases/goodsreceipt", pd.ListGoodsReceipt).Methods(http.MethodGet)
	api.HandleFunc("/purchases/goodsreceipt", pd.CreateGoodsReceipt).Methods(http.MethodPost)
	api.HandleFunc("/purchases/goodsreceipt/{idDoc}/pdf", pd.GetGoodsReceiptPDF).Methods(http.MethodGet)
	api.HandleFunc("/purchases/goodreceiptstoinvoice", pd.GoodsReceiptsToInvoice).Methods(http.MethodPost)
	api.HandleFunc("/purchases/invoices", pd.ListInvoices).Methods(http.MethodGet)
	api.HandleFunc("/purchases/invoices", pd.CreateInvoice).Methods(http.MethodPost)
	api.HandleFunc("/purchases/invoices/openbalance", pd.OpenBalance).Methods(http.MethodGet)
	api.HandleFunc("/purchases/invoices/{idDoc}/pdf", pd.GetInvoicePDF).Methods(http.MethodGet)
	api.HandleFunc("/purchases/vendorpayment", pd.ListVendorPayments).Methods(http.MethodGet)
	api.HandleFunc("/purchases/vendorpayment", pd.CreateVendorPayment).Methods(http.MethodPost)
	api.HandleFunc("/purchases/vendorpayment/{id}", pd.GetVendorPaymentByID).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{idDoc}/pdf", pd.GetDocumentPDF).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{idDoc}/attachment", pd.GetAttachment).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{idDoc}/attachment", pd.UploadAttachment).Methods(http.MethodPost)
	api.HandleFunc("/purchases/{idDoc}/attachment", pd.DeleteAttachment).Methods(http.MethodDelete)
	api.HandleFunc("/purchases/{idDoc}/vendorpayment", pd.GetVendorPaymentByDoc).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{id}/orders", pd.GetOrder).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{id}/orders", pd.UpdateOrder).Methods(http.MethodPut)
	api.HandleFunc("/purchases/{id}/goodsreceipt", pd.GetGoodsReceipt).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{id}/goodsreceipt", pd.UpdateGoodsReceipt).Methods(http.MethodPut)
	api.HandleFunc("/purchases/{id}/goodsreceipt", pd.DeleteGoodsReceipt).Methods(http.MethodDelete)
	api.HandleFunc("/purchases/{id}/invoices", pd.GetInvoice).Methods(http.MethodGet)
	api.HandleFunc("/purchases/{id}/invoices", pd.UpdateInvoice).Methods(http.MethodPut)
	api.HandleFunc("/purchases/{id}/invoices", pd.DeleteInvoice).Methods(http.MethodDelete)
	api.HandleFunc("/purchases/{id}/vendorpayment", pd.UpdateVendorPayment).Methods(http.MethodPut)
	api.HandleFunc("/purchases/{id}/vendorpayment", pd.DeleteVendorPayment).Methods(http.MethodDelete)

	ac := handlers.NewAccountingHandler(appServices.Accounting)
	api.HandleFunc("/accounting/accountmovements", ac.ListAccountMovements).Methods(http.MethodGet)
	api.HandleFunc("/accounting/accountmovements", ac.CreateAccountMovement).Methods(http.MethodPost)
	api.HandleFunc("/accounting/accountmovements", ac.UpdateAccountMovement).Methods(http.MethodPut)
	api.HandleFunc("/accounting/{idDoc}/accountmovements", ac.DeleteAccountMovement).Methods(http.MethodDelete)

	cr := handlers.NewCrmHandler(appServices.Crm)
	api.HandleFunc("/crmaccounts", cr.CreateAccount).Methods(http.MethodPost)
	api.HandleFunc("/crmaccounts/report", cr.GlobalReport).Methods(http.MethodGet)
	api.HandleFunc("/crmaccounts/tasks", cr.ListAllTasks).Methods(http.MethodGet)
	api.HandleFunc("/crmaccounts/{idcrmaccount}/report", cr.AccountReport).Methods(http.MethodGet)
	api.HandleFunc("/crmaccounts/{idcrmaccount}/tasks", cr.ListAccountTasks).Methods(http.MethodGet)
	api.HandleFunc("/crmaccounts/{idParent}/activities-attachments", cr.UploadActivityAttachment).Methods(http.MethodPost)
	api.HandleFunc("/crmaccounts/{idParent}/activities", cr.ListActivities).Methods(http.MethodGet)
	api.HandleFunc("/crmaccounts/{idParent}/activities", cr.CreateActivity).Methods(http.MethodPost)
	api.HandleFunc("/crmaccounts/{idParent}/activities/{id}", cr.GetActivity).Methods(http.MethodGet)
	api.HandleFunc("/crmaccounts/{idParent}/activities/{id}", cr.UpdateActivity).Methods(http.MethodPut)
	api.HandleFunc("/crmaccounts/{idParent}/activities/{id}", cr.PatchActivity).Methods(http.MethodPatch)
	api.HandleFunc("/crmaccounts/{idParent}/activities/{id}", cr.DeleteActivity).Methods(http.MethodDelete)
	api.HandleFunc("/crmaccounts/{idParent}/tasks", cr.CreateTask).Methods(http.MethodPost)
	api.HandleFunc("/crmaccounts/{idParent}/tasks/{id}", cr.UpdateTask).Methods(http.MethodPut)
	api.HandleFunc("/crmaccounts/{idParent}/tasks/{id}", cr.PatchTask).Methods(http.MethodPatch)
	api.HandleFunc("/crmaccounts/{idParent}/tasks/{id}", cr.DeleteTask).Methods(http.MethodDelete)
	api.HandleFunc("/crmaccounts/{idTask}", cr.GetTask).Methods(http.MethodGet)

	cal := handlers.NewCalendarHandler(appServices.Calendar)
	api.HandleFunc("/calendars", cal.ListCalendars).Methods(http.MethodGet)
	api.HandleFunc("/calendars/events", cal.ListEvents).Methods(http.MethodGet)
	api.HandleFunc("/calendars/events", cal.CreateEvent).Methods(http.MethodPost)
	api.HandleFunc("/calendars/events/{id}", cal.GetEvent).Methods(http.MethodGet)
	api.HandleFunc("/calendars/events/{id}", cal.UpdateEvent).Methods(http.MethodPut)
	api.HandleFunc("/calendars/events/{id}", cal.DeleteEvent).Methods(http.MethodDelete)

	pa := handlers.NewPersonalActivityHandler(appServices.PersonalActivity)
	api.HandleFunc("/personalactivities", pa.List).Methods(http.MethodGet)
	api.HandleFunc("/personalactivities", pa.Create).Methods(http.MethodPost)
	api.HandleFunc("/personalactivities/{id}", pa.Get).Methods(http.MethodGet)
	api.HandleFunc("/personalactivities/{id}", pa.Update).Methods(http.MethodPut)
	api.HandleFunc("/personalactivities/{id}", pa.Patch).Methods(http.MethodPatch)
	api.HandleFunc("/personalactivities/{id}", pa.Delete).Methods(http.MethodDelete)

	us := handlers.NewUserHandler(appServices.User)
	api.HandleFunc("/users", us.ListUsers).Methods(http.MethodGet)
	api.HandleFunc("/users", us.CreateUser).Methods(http.MethodPost)
	api.HandleFunc("/users/agentcommission", us.ListAgentCommissions).Methods(http.MethodGet)
	api.HandleFunc("/users/{idUser}/authprofiles", us.AddAuthProfiles).Methods(http.MethodPost)
	api.HandleFunc("/users/{id}", us.GetUser).Methods(http.MethodGet)
	api.HandleFunc("/users/{id}", us.UpdateUser).Methods(http.MethodPut)
	api.HandleFunc("/users/{id}", us.DeleteUser).Methods(http.MethodDelete)

	st := handlers.NewSettingsHandler(appServices.Settings)
	api.HandleFunc("/settings", st.ListSettings).Methods(http.MethodGet)
	api.HandleFunc("/settings", st.UpsertSetting).Methods(http.MethodPost)

	withAuth := middleware.AuthMiddleware(appServices.Auth)(router)
	return middleware.CorsMiddleware(cfg.CORSOriginsList())(withAuth)
}
